### ISSUE TITLE
Deploy OpenStack Fuel for PXE booting the Orange cluster

### ISSUE THREAD

**Issue by ianblenke** [sofwerx/swx-devops#8]
Deploy crowbar/cobbler to the first blade in the Orange cluster, setup leases for cameras/gear on the SWX-Data segment, disable the existing Araknis router DHCP

**Comment by ianblenke** [comment]
OpenStack Fuel 11.0 Liberty  is installed on swx-u-or-node0
The swx-u-or-node[1-7] nodes are DHCP booting from cobbler successfully.

**Comment by swxdevops** [comment]
Fuel is dead. Mirantis killed it.
